-- UI translations; skill names and icons come from the selected game client.
Strings = {
 fr = {
 title="Bienvenue en Terre du Milieu", level="%s — niveau %d", next="Compétences non apprises, par niveau requis",
 levelUpTitle="Vous avez gagné un niveau!", levelUpMessage="Félicitations %s, tu es maintenant au niveau %d!", playerFallback="Aventurier",
 levelUpObtainedTitle="Ce que tu viens d'obtenir au niveau %d :", levelUpObtainedRangeTitle="Ce que tu viens d'obtenir des niveaux %d à %d :", levelUpObtainedEmpty="Aucun nouveau sort ou point de trait détecté à ce niveau.",
 levelUpUpcomingTitle="Ce qui t'attend dans les prochains niveaux :", levelUpUpcomingEmpty="Aucun prochain palier de compétence ou de trait n'est détecté.", levelUpGainedRow="%s", levelUpRow="%s à partir du niveau %d", traitPointName="Point de trait de classe",
 row="Niv. %d — %s", ready="Niv. %d — %s (vérifie les autres prérequis)",
 mountedRow="Niv. %d — %s [Combat monté]", mountedReady="Niv. %d — %s [Combat monté — vérifie les autres prérequis]",
 empty="Aucune compétence non apprise n'est signalée par le jeu. Les compétences de spécialisation peuvent dépendre de tes traits.",
 error="La liste des compétences est indisponible ou incomplète. Clique sur Actualiser ou consulte le panneau Compétences du jeu.",
 skipped="Certaines compétences n'ont pas de niveau exploitable ; elles ne sont pas affichées.",
 filtered="Les compétences hors progression automatique de classe sont masquées ; le combat monté de niveau 75 est conservé.",
 note="Les niveaux ne garantissent pas l'accès : traits, quêtes ou autres prérequis peuvent intervenir.",
 trait="Prochain point de trait : niveau %d.", traitEnd="Consulte tes traits pour vérifier tes points disponibles.",
 refresh="Actualiser", previous="Précédent", following="Suivant", page="%d / %d", guide="Guide légendaire", close="Fermer", options="Options", optionsTitle="WelcomeToMiddleEarth — Options",
 auto="Afficher à chaque niveau", scenes="Étapes illustrées", traits="Repères de traits",
 loaded="WelcomeToMiddleEarth 1.4.16-community chargé. /wtme pour ouvrir le suivi.",
 help="/wtme : ouvrir ; /wtme levelup : réafficher le dernier gain de niveau ; /wtme help : guide légendaire ; /wtme diagnostic : état de lecture des compétences.",
 levelUpNoneSaved="Aucun gain de niveau mémorisé pour ce personnage.", saveFailed="WelcomeToMiddleEarth : impossible de sauvegarder les données de ce personnage. Les changements risquent d’être perdus après un /reload ou une déconnexion.",
 diagnostic="WTME : %d compétences ; %d entrées filtrées ; %d entrées sans niveau exploitable ; lecture incomplète : %s.",
 intro="Objets légendaires : les repères utiles",
 guideText="À partir du niveau 45, tu peux commencer l'introduction de la Moria auprès de Ráthwald à Echad Dúnann, en Eregion. Suis cette introduction pour obtenir tes premiers objets légendaires.\n\nLes objets légendaires actuels utilisent des gravures. À Fondcombe, les archives de la dernière maison simple proposent des échanges liés à ce système. La reforge fait progresser ton objet ; les runes d'amélioration font progresser ses emplacements de gravures. Vérifie les limites de niveau affichées sur chaque objet.\n\nDepuis la mise à jour 38, la rareté d'une rune détermine le nombre de niveaux gagnés. Les anciennes limites différentes selon la rareté d'une rune, à l'intérieur d'une même tranche, ne s'appliquent plus.\n\nLe parcours de récompenses légendaires est accessible à partir du niveau 45 : Menu > Personnage > Parcours de récompenses. Ses saisons changent ; consulte les dates affichées en jeu.\n\nLa progression ne s'arrête plus à 140 : Corsairs of Umbar accompagne les niveaux 140 à 150, puis Kingdoms of Harad porte le plafond des mondes classiques à 160. Les mondes légendaires ont leur propre plafond.\n\nLes anciennes instructions de migration des armes d'avant 2021 ne sont pas nécessaires pour un nouveau personnage.",
 umbar="Niveau 140 : la progression continue avec Corsairs of Umbar (140–150), selon les contenus auxquels tu as accès.",
 harad="Niveau 150 : Kingdoms of Harad poursuit l'aventure jusqu'au niveau 160, selon les contenus auxquels tu as accès.",
 cap="Niveau 160 : plafond des mondes classiques confirmé par les notes consultées. Les mondes légendaires peuvent avoir un autre plafond.",
 details="Détails de la compétence"
 },
 en = {
 title="Welcome to Middle-earth", level="%s — level %d", next="Untrained skills, ordered by required level",
 levelUpTitle="You've leveled up!", levelUpMessage="Congratulations %s, you are now level %d!", playerFallback="Adventurer",
 levelUpObtainedTitle="What you just gained at level %d:", levelUpObtainedRangeTitle="What you just gained from levels %d to %d:", levelUpObtainedEmpty="No new skill or class trait point was detected at this level.",
 levelUpUpcomingTitle="What awaits you in the next levels:", levelUpUpcomingEmpty="No upcoming skill or trait milestone was detected.", levelUpGainedRow="%s", levelUpRow="%s from level %d", traitPointName="Class Trait Point",
 row="Level %d — %s", ready="Level %d — %s (check other requirements)",
 mountedRow="Level %d — %s [Mounted combat]", mountedReady="Level %d — %s [Mounted combat — check other requirements]",
 empty="The game reports no untrained skills. Specialization skills may depend on your traits.",
 error="The skill list is unavailable or incomplete. Click Refresh or check the game's Skills panel.",
 skipped="Some skills have no usable level requirement and are not displayed.",
 filtered="Skills outside automatic class progression are hidden; level-75 mounted combat is kept.",
 note="Level alone does not guarantee access: traits, quests or other requirements may apply.",
 trait="Next class trait point: level %d.", traitEnd="Check your traits for available points.",
 refresh="Refresh", previous="Previous", following="Next", page="%d / %d", guide="Legendary guide", close="Close", options="Options", optionsTitle="WelcomeToMiddleEarth — Options",
 auto="Show on level up", scenes="Illustrated milestones", traits="Trait reminders",
 loaded="WelcomeToMiddleEarth 1.4.16-community loaded. Use /wtme to open.",
 help="/wtme: open; /wtme levelup: reopen the last level-up; /wtme help: legendary guide; /wtme diagnostic: skill reading status.",
 levelUpNoneSaved="No saved level-up is available for this character yet.", saveFailed="WelcomeToMiddleEarth: unable to save data for this character. Changes may be lost after /reload or logout.",
 diagnostic="WTME: %d skills; %d filtered entries; %d entries without usable levels; incomplete reading: %s.",
 intro="Legendary items: useful milestones",
 guideText="From level 45 you can begin the Moria introduction with Rathwald at Echad Dunann in Eregion. Follow the introduction to obtain your first legendary items.\n\nCurrent legendary items use traceries. The archive in Rivendell's Last Homely House offers related barter services. Reforging advances your item; enhancement runes improve its tracery slots. Check the level limits on each item.\n\nSince Update 38, rune rarity determines the number of levels gained. The old separate rarity caps within the same level band no longer apply.\n\nThe Legendary Items Reward Track is available from level 45: Menu > Character > Reward Track. Seasons change; check the dates in game.\n\nProgression no longer ends at 140: Corsairs of Umbar covers levels 140–150, and Kingdoms of Harad raises the standard world cap to 160. Legendary worlds have their own caps.\n\nA new character does not need the old migration instructions for pre-2021 weapons.",
 umbar="Level 140: continue through Corsairs of Umbar (140–150), subject to content access.",
 harad="Level 150: Kingdoms of Harad continues the adventure to level 160, subject to content access.",
 cap="Level 160: standard world cap confirmed in the reviewed notes. Legendary worlds can have a different cap.", details="Skill details"
 },
 de = {
 title="Willkommen in Mittelerde", level="%s — Stufe %d", next="Ungelernte Fertigkeiten nach erforderlicher Stufe",
 levelUpTitle="Du bist aufgestiegen!", levelUpMessage="Herzlichen Glückwunsch %s, du bist nun Stufe %d!", playerFallback="Abenteurer",
 levelUpObtainedTitle="Das hast du auf Stufe %d gerade erhalten:", levelUpObtainedRangeTitle="Das hast du von Stufe %d bis %d erhalten:", levelUpObtainedEmpty="Auf dieser Stufe wurde keine neue Fertigkeit und kein Eigenschaftspunkt erkannt.",
 levelUpUpcomingTitle="Das erwartet dich in den nächsten Stufen:", levelUpUpcomingEmpty="Es wurde kein weiterer Fertigkeits- oder Eigenschaftspunkt-Meilenstein erkannt.", levelUpGainedRow="%s", levelUpRow="%s ab Stufe %d", traitPointName="Klasseneigenschaftspunkt",
 row="Stufe %d — %s", ready="Stufe %d — %s (weitere Voraussetzungen prüfen)",
 mountedRow="Stufe %d — %s [Berittener Kampf]", mountedReady="Stufe %d — %s [Berittener Kampf — weitere Voraussetzungen prüfen]",
 empty="Das Spiel meldet keine ungelernten Fertigkeiten. Spezialisierungsfertigkeiten können von Eigenschaften abhängen.",
 error="Die Fertigkeitenliste ist nicht verfügbar oder unvollständig. Bitte aktualisieren oder das Fertigkeitenfenster im Spiel prüfen.",
 skipped="Einige Fertigkeiten haben keine verwertbare Stufenanforderung und werden nicht angezeigt.",
 filtered="Fertigkeiten außerhalb der automatischen Klassenentwicklung werden ausgeblendet; berittener Kampf auf Stufe 75 bleibt erhalten.",
 note="Die Stufe allein genügt nicht immer: Eigenschaften, Aufgaben oder andere Voraussetzungen können gelten.",
 trait="Nächster Klasseneigenschaftspunkt: Stufe %d.", traitEnd="Prüft eure Eigenschaften auf verfügbare Punkte.",
 refresh="Aktualisieren", previous="Zurück", following="Weiter", page="%d / %d", guide="Legendäre Gegenstände", close="Schließen", options="Optionen", optionsTitle="WelcomeToMiddleEarth — Optionen",
 auto="Bei Stufenaufstieg zeigen", scenes="Bebilderte Meilensteine", traits="Eigenschaftspunkte",
 loaded="WelcomeToMiddleEarth 1.4.16-community geladen. Mit /wtme öffnen.",
 help="/wtme: öffnen; /wtme levelup: letzten Stufenaufstieg erneut anzeigen; /wtme help: legendäre Gegenstände; /wtme diagnostic: Fertigkeitenstatus.",
 levelUpNoneSaved="Für diesen Charakter ist noch kein Stufenaufstieg gespeichert.", saveFailed="WelcomeToMiddleEarth: Die Daten dieses Charakters konnten nicht gespeichert werden. Änderungen können nach /reload oder Abmeldung verloren gehen.",
 diagnostic="WTME: %d Fertigkeiten; %d gefilterte Einträge; %d Einträge ohne nutzbare Stufe; unvollständige Abfrage: %s.",
 intro="Legendäre Gegenstände: wichtige Hinweise",
 guideText="Ab Stufe 45 könnt ihr die Moria-Einführung bei Rathwald in Echad Dunann in Eregion beginnen. Folgt der Einführung für eure ersten legendären Gegenstände.\n\nAktuelle legendäre Gegenstände verwenden Filigranmuster. Im Archiv im Letzten Heimeligen Haus in Bruchtal gibt es passende Tauschhändler. Umschmieden verbessert den Gegenstand; Verbesserungsrunen verbessern seine Musterplätze. Beachtet die Stufengrenzen der Gegenstände.\n\nSeit Update 38 bestimmt die Seltenheit der Rune die Anzahl der gewonnenen Stufen. Die alten unterschiedlichen Seltenheitsgrenzen innerhalb eines Stufenbereichs gelten nicht mehr.\n\nDie Belohnungsleiste für legendäre Gegenstände ist ab Stufe 45 verfügbar: Menü > Charakter > Belohnungsleiste. Beachtet die aktuellen Saisontermine im Spiel.\n\nDie Entwicklung endet nicht mehr bei 140: Corsairs of Umbar umfasst Stufe 140–150, Kingdoms of Harad erhöht die Grenze normaler Welten auf 160. Legendäre Welten haben eigene Grenzen.\n\nNeue Charaktere brauchen die alten Umstellungsanweisungen für Waffen von vor 2021 nicht.",
 umbar="Stufe 140: Corsairs of Umbar führt bis Stufe 150, sofern ihr Zugang zu den Inhalten habt.",
 harad="Stufe 150: Kingdoms of Harad führt bis Stufe 160, sofern ihr Zugang zu den Inhalten habt.",
 cap="Stufe 160: bestätigte Grenze normaler Welten. Legendäre Welten können andere Grenzen haben.", details="Fertigkeitsdetails"
 }
}
